### ISSUE TITLE
Unhandled exception in GMusicBackend

### ISSUE THREAD

**Issue by shuricksumy** [hechtus/mopidy-gmusic#86]
Hi,
please update mopidy-gmusic according to last changes in Unofficial-Google-Music-API

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/actor.py", line 48, in on_start
    self.config['gmusic']['deviceid'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 21, in login
    if not self.api.login(username, password):
TypeError: login() takes exactly 4 arguments (3 given)

**Comment by shuricksumy** [comment]
Hi,
according to Commits on Jun 2, 2015 in Unofficial-Google-Music-API - this issue is not reproduced. Authentication is ok now.

**Comment by NellyWhadsDev** [comment]
Hello, how did you end up fixing this issue? I am having the same one.

**Comment by shuricksumy** [comment]
Hi. Unofficial-Google-Music-API uses parameter "deviceid" for authorization again. You can ease fix it:
/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py
```
@@ -18,7 +18,7 @@
         if self.api.is_authenticated():
             self.api.logout()
 
-        if not self.api.login(username, password):
+        if not self.api.login(username, password, deviceid):
             logger.error(u'Failed to login as "%s"', username)
 
         if self.api.is_authenticated():
```

**Comment by NellyWhadsDev** [comment]
Good catch - I was thinking of just adding the parameter as well but was not sure if that was the best idea.

Thanks!

**Comment by NellyWhadsDev** [comment]
Followup error: it seems that it wasn't that easy: I now get an error that self.api.login(username, password, deviceid) takes exactly 3 arguments, and that 4 are given. Here is the error response when starting up mopidy:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/actor.py", line 29, in on_start
    self.config['gmusic']['deviceid'])
  File "/usr/local/lib/python2.7/dist-packages/mopidy_gmusic/session.py", line 21, in login
    self.api.login(username, password, deviceid)
TypeError: login() takes exactly 3 arguments (4 given)
2015-06-19 05:13:52,695 INFO [17903:MainThread] mopidy.commands: Starting Mopidy core
2015-06-19 05:13:52,711 ERROR [17903:MainThread] mopidy.commands: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 275, in run
    core = self.start_core(mixer, backends, audio)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 364, in start_core
    return Core.start(mixer=mixer, backends=backends, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 52, in __init__
    self.backends = Backends(backends)
  File "/usr/lib/python2.7/dist-packages/mopidy/core/actor.py", line 151, in __init__
    has_library = b.has_library().get()
  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 470, in ask
    self.tell(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)

Below is a snippet of the change I made:

    def login(self, username, password, deviceid):
        if self.api.is_authenticated():
            self.api.logout()
        try:
            self.api.login(username, password, deviceid)
        except CallFailure as error:
            logger.error(u'Failed to login as "%s": %s', username, error)
        if self.api.is_authenticated():
            if deviceid is None:
                self.deviceid = self.get_deviceid(username, password)
            else:
                self.deviceid = deviceid
        else:
            return False

As you can see, I simply added a parameter to the function. Are there any recompilation steps I have to take? (Sorry, never worked in python before mopidy setup :(

**Comment by shuricksumy** [comment]
Hi. Actually I use parameter "deviceid" in my config file. So it is defined.
How to get this parameter: you can use app https://play.google.com/store/apps/details?id=com.evozi.deviceid. Or run script: https://github.com/hechtus/squeezebox-googlemusic/blob/master/mobile_devices.py
About error (TypeError: login() takes exactly 3 arguments (4 given)):
Unofficial-Google-Music-API (Commits on Jun 13, 2015 ) login() uses 4 arguments
(Commits on Jun 3, 2015 ) login() uses 3 arguments.
So you shuld update Unofficial-Google-Music-API to latest (branch develop) or you should revert change which I proposed. But parameter "deviceid" should be defined in config file.

**Comment by NellyWhadsDev** [comment]
I've made sure to define the deviceid in my config file - so that error seems to best me as of now.

Just pip installed the develop branch of the unofficial api - it all works! 

Many thanks indeed - NellyWhads

**Comment by abarreir** [comment]
Fix has been pushed.
