### ISSUE TITLE
Showing songs doesn't work

### ISSUE THREAD

**Issue by nielsk** [hechtus/mopidy-gmusic#94]
For getting mopidy_gmusic at all, I did the following: I installed the current gmusicapi and then the developer-branch of mopidy_gmusic. Then I edited the session.py, so that line 21 reads:
```
if not self.api.login(username, password, deviceid):
```
(device-id was missing before)

Starting mopidy with gmusic works but when I navigate into an artist or album in ncmpcpp where songs would usually show up, I get the following errors:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/repeating_timer.py", line 12, in run
    self._method()
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/actor.py", line 78, in _refresh_library
    self.playlists.refresh()
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/playlists.py", line 50, in refresh
    for track in self.backend.session.get_thumbs_up_songs():
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/session.py", line 71, in get_thumbs_up_songs
    return self.api.get_thumbs_up_songs()
AttributeError: 'Mobileclient' object has no attribute 'get_thumbs_up_songs'

ERROR    Unhandled exception in MpdSession (urn:uuid:ecf2e6ac-bfbc-493a-91f1-f0c1c90095ab):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 303, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/site-packages/mopidy/utils/network.py", line 367, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/session.py", line 33, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 46, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 75, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 85, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 104, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 133, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 146, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 67, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 158, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 172, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 178, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/__init__.py", line 156, in validate
    return func(**callargs)
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/protocol/music_db.py", line 357, in lsinfo
    for path, lookup_future in context.browse(uri, recursive=False):
  File "/usr/lib/python2.7/site-packages/mopidy/mpd/dispatcher.py", line 299, in browse
    for ref in future.get():
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 78, in browse
    return backend.library.browse(uri).get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 105, in browse
    return self._browse_album(uri)
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 58, in _browse_album
    for track in self._lookup_album(uri):
  File "/usr/lib/python2.7/site-packages/mopidy_gmusic/library.py", line 210, in _lookup_album
    tracks = self.find_exact(
AttributeError: 'GMusicLibraryProvider' object has no attribute 'find_exact'
```

And this repeats then over and over again and ncmpcpp shows a timeout

**Comment by nielsk** [comment]
Pull request #88 which changes find_exact to _find_exact worked for me

**Comment by abarreir** [comment]
Pull request #88 just merged.
